image: mono

stages:
    - build

build:release:
    stage: build
    only:
        - master
    script:
        - msbuild "Kundenverwaltung.sln" /p:Configuration=Release /p:Platform="Any CPU"

build:debug:
    stage: build
    script:
        - msbuild "Kundenverwaltung.sln" /p:Configuration=Debug /p:Platform="Any CPU"

