image: mono

stages:
    - build

build:release:
    stage: build
    only:
        - master
    script:
        - xbuild "Kundenverwaltung.sln" /p:Configuration=Release /p:Platform=x86

build:debug:
    stage: build
    script:
        - xbuild "Kundenverwaltung.sln" /p:Configuration=Debug /p:Platform=x86

